-- Creating FACULTY table

CREATE TABLE FACULTY (
FACULTY_ID INT NOT NULL PRIMARY KEY,
DEPARTMENT_ID INT NOT NULL,
STUDENT_ID INT NOT NULL,
FACULTY_NAME VARCHAR(25) NOT NULL,
DEAN VARCHAR(25)
);

-- Added Foreign Keys (DEPARTMENT_ID) and (STUDENT_ID)
-- after created the DEPARTMENT and STUDENT tables

ALTER TABLE FACULTY
ADD CONSTRAINT FK_DEPARTMENT
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID);

ALTER TABLE FACULTY
ADD CONSTRAINT FK_STUDENT
FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID);

-- Creating DEPARTMENT table

CREATE TABLE DEPARTMENT (
DEPARTMENT_ID INT NOT NULL PRIMARY KEY,
COURSE_ID INT NOT NULL,
DEPARTMENT_NAME VARCHAR(25) NOT NULL
);

-- Added Foreign Key (COURSE_ID) after created the COURSE table
ALTER TABLE DEPARTMENT
ADD CONSTRAINT FK_COURSE
FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID);

-- Creating STUDENT table

CREATE TABLE STUDENT (
STUDENT_ID INT NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR2(25),
LAST_NAME VARCHAR2(25),
ADDRESS VARCHAR2(25),
DATE_OF_BIRTH DATE,
PHONE VARCHAR2(25),
GENDER VARCHAR2(25),
AGE INT);

-- Creating COURSE table

CREATE TABLE COURSE (
COURSE_ID INT NOT NULL PRIMARY KEY,
COURSE_NAME VARCHAR2(15),
SECTION INT,
SEMESTER VARCHAR(15));

-- Added Foreign Key (INSTRUCTOR_ID) after created the INSTRUCTOR table

ALTER TABLE COURSE
ADD CONSTRAINT FK_INSTRUCTOR
FOREIGN KEY (INSTRUCTOR_ID) REFERENCES INSTRUCTOR(INSTRUCTOR_ID);

-- Creating INSTRUCTOR table

CREATE TABLE INSTRUCTOR ( INSTRUCTOR_ID INT NOT NULL PRIMARY KEY,
                            FIRST_NAME VARCHAR2(25),
LAST_NAME VARCHAR2(25),
EMAIL VARCHAR2(25),
ADDRESS VARCHAR2(25),
DATE_OF_BIRTH DATE,
PHONE VARCHAR2(25),
GENDER VARCHAR2(25),
AGE INT);

--Creating GRADE table

CREATE TABLE GRADE(
LETTER_GRADE VARCHAR2(2) NOT NULL PRIMARY KEY,
STUDENT_ID INT NOT NULL,
COURSE_ID INT NOT NULL,
SCORE VARCHAR2(25));

-- Added Foreign Keys (COURSE_ID) and (STUDENT_ID)
-- after created the STUDENT and COURSE tables

ALTER TABLE GRADE
ADD CONSTRAINT FK_COURSE0
FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID);
ALTER TABLE GRADE
ADD CONSTRAINT FK_STUDENT0
FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID);
